<a href="https://colab.research.google.com/github/Nishtha110606/Refftonix-Projects/blob/main/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X= df.drop('species',axis=1)
y= df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train,y_train)
model_knn.score(X_test,y_test)

0.98

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC (gamma='auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
#now lets use the grid search cv

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00651693, 0.00594406, 0.00486751, 0.00473194, 0.00479918,
        0.00632935]),
 'std_fit_time': array([0.00055309, 0.0014908 , 0.00071259, 0.00036166, 0.00087962,
        0.00241213]),
 'mean_score_time': array([0.00877981, 0.00353308, 0.00362697, 0.00422149, 0.00442605,
        0.00386324]),
 'std_score_time': array([0.00393558, 0.00026509, 0.00031533, 0.00048318, 0.000622  ,
        0.00051606]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 ]),
 'rank_test_score': array([2, 1, 3, 4, 6, 4], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006517,0.000553,0.008780,0.003936,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.005944,0.001491,0.003533,0.000265,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.004868,0.000713,0.003627,0.000315,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,3
3,0.004732,0.000362,0.004221,0.000483,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,4
4,0.004799,0.000880,0.004426,0.000622,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,6
5,0.006329,0.002412,0.003863,0.000516,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,4

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.94
1        1       linear             0.95
2       10          rbf             0.93
3       10       linear             0.93
4       20          rbf             0.92
5       20       linear             0.93

In [ ]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors':[1,5,10,3,7,9]
},cv=5,return_train_score=False)

In [ ]:
classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 5, 10, 3, 7, 9]})

In [ ]:
classifier2.cv_results_

{'mean_fit_time': array([0.00353627, 0.00324073, 0.00337219, 0.00346956, 0.00351696,
        0.00325384]),
 'std_fit_time': array([0.00031863, 0.00012383, 0.00016098, 0.00013927, 0.00012525,
        0.00019543]),
 'mean_score_time': array([0.00552268, 0.004635  , 0.0050456 , 0.00483255, 0.00490036,
        0.00459943]),
 'std_score_time': array([0.0018965 , 0.00037149, 0.00026421, 0.00026664, 0.00010615,
        0.00026024]),
 'param_n_neighbors': masked_array(data=[1, 5, 10, 3, 7, 9],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 5},
  {'n_neighbors': 10},
  {'n_neighbors': 3},
  {'n_neighbors': 7},
  {'n_neighbors': 9}],
 'split0_test_score': array([0.95, 0.9 , 0.9 , 0.95, 0.9 , 0.9 ]),
 'split1_test_score': array([0.9 , 0.9 , 0.9 , 0.85, 0.9 , 0.9 ]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split4_test_score': array([0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.94, 0.93, 0.93, 0.93, 0.93, 0.93]),
 'std_test_score': array([0.03741657, 0.04      , 0.04      , 0.0509902 , 0.04      ,
        0.04      ]),
 'rank_test_score': array([1, 2, 2, 6, 2, 2], dtype=int32)}

In [ ]:
df = pd.DataFrame(classifier2.cv_results_)

In [ ]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003536,0.000319,0.005523,0.001897,1,{'n_neighbors': 1},0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
1,0.003241,0.000124,0.004635,0.000371,5,{'n_neighbors': 5},0.90,0.90,0.9,1.0,0.95,0.93,0.040000,2
2,0.003372,0.000161,0.005046,0.000264,10,{'n_neighbors': 10},0.90,0.90,0.9,1.0,0.95,0.93,0.040000,2
3,0.003470,0.000139,0.004833,0.000267,3,{'n_neighbors': 3},0.95,0.85,0.9,1.0,0.95,0.93,0.050990,6
4,0.003517,0.000125,0.004900,0.000106,7,{'n_neighbors': 7},0.90,0.90,0.9,1.0,0.95,0.93,0.040000,2
5,0.003254,0.000195,0.004599,0.000260,9,{'n_neighbors': 9},0.90,0.90,0.9,1.0,0.95,0.93,0.040000,2

In [ ]:
df[['param_n_neighbors','mean_test_score']]

   param_n_neighbors  mean_test_score
0                  1             0.94
1                  5             0.93
2                 10             0.93
3                  3             0.93
4                  7             0.93
5                  9             0.93

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=5)

In [ ]:
classifier_r.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
classifier_r.score(X_test,y_test)

1.0

In [ ]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00412292, 0.00401239, 0.00378151, 0.00391693, 0.00368443]),
 'std_fit_time': array([2.85871508e-04, 2.84250961e-04, 1.64483345e-04, 9.35996726e-05,
        1.39667306e-03]),
 'mean_score_time': array([0.0030035 , 0.00304828, 0.00294185, 0.00297093, 0.00245967]),
 'std_score_time': array([1.01568397e-04, 1.80577457e-04, 5.48200998e-05, 1.05894679e-04,
        9.47220501e-04]),
 'param_kernel': masked_array(data=['linear', 'linear', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 20, 1, 20, 10],
              mask=[False, False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 30},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95]),
 'split1_test_score': array([0.85, 0.85, 0.9 , 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 0.95, 1.  , 1.  , 1.  ]),
 'split4_test_score': array([1.  , 1.  , 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.94, 0.93, 0.95, 0.92, 0.93]),
 'std_test_score': array([0.05830952, 0.0509902 , 0.04472136, 0.0678233 , 0.0509902 ]),
 'rank_test_score': array([2, 3, 1, 5, 3], dtype=int32)}

In [ ]:
df = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004123,0.000286,0.003004,0.000102,linear,30,"{'kernel': 'linear', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
1,0.004012,0.000284,0.003048,0.000181,linear,20,"{'kernel': 'linear', 'C': 20}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,3
2,0.003782,0.000164,0.002942,0.000055,linear,1,"{'kernel': 'linear', 'C': 1}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
3,0.003917,0.000094,0.002971,0.000106,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,5
4,0.003684,0.001397,0.002460,0.000947,linear,10,"{'kernel': 'linear', 'C': 10}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,3

In [ ]:
df = df[['param_C','param_kernel','mean_test_score']]

In [ ]:
df

   param_C param_kernel  mean_test_score
0       30       linear             0.94
1       20       linear             0.93
2        1       linear             0.95
3       20          rbf             0.92
4       10       linear             0.93